[package]
name = "shazamdown"
version = "0.1.0"
edition = "2024"
license = "GPLv3"
description = "Convert documents, presentations, spreadsheets, and more to markdown files."
keywords = ["markdown", "document", "convert", "gui"]
repository = "https://github.com/kaden126/shazamdown"

[dependencies]
anyhow = "1.0.104"
office_oxide = "0.1.8"
rfd = "0.17.2"
slint = "1.17.1"


[build-dependencies]
slint-build = "1.17.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
